### PR TITLE
Enhance mapepire-js documentation

### PR DESCRIPTION
**Pull request by jwoehr**
- document aspects of the mapepire-js client and its relation to the mapepire-server and IBM i Db2
- describe connecting from the client to the server using ssh port redirection

### CODE REVIEW

**Review by worksofliam — CHANGES_REQUESTED** [review]
@jwoehr I don't believe your setup guides belongs in that Node.js page. I recommend you create a new page, under a 'project' folder which will be for contributors like yourself.

The Node.js page you edited will be for actually consuming the library when it's published.

**Comment by jwoehr** [comment]
> @jwoehr I don't believe your setup guides belongs in that Node.js page. I recommend you create a new page, under a 'project' folder which will be for contributors like yourself.
Sure, @worksofliam ... put the folder under `guides` or in a folder, say, `usernotes` peer to `guides`?

**Comment by worksofliam** [comment]
@jwoehr I think `guides` would be good!

**Comment by jwoehr** [comment]
Ok, @worksofliam , `usernotes` in `guides` it is.

**Comment by jwoehr** [comment]
It says it's merged but I can't find the ssh_redirect.md file nor the usernotes directory anywhere @ThePrez ?!

**Comment by ThePrez** [comment]
Should be on main, just switch branch and pull 😊

**Comment by jwoehr** [comment]
I don't see it @ThePrez , neither when I pull from upstream nor when I browse code here on Github.

**Comment by jwoehr** [comment]
There's no src/content/docs/guides/usernotes/ssh_redirect.md Or maybe I'm just losing my mind :)

**Comment by worksofliam** [comment]
@jwoehr it was moved to another directory and renamed in a new commit!

**Comment by jwoehr** [comment]
aha ... I see it now src/content/docs/reference/Maintenance/sshRedirect.md

"never mind" :)

**Pull request merged**
